### ISSUE TITLE
Craft 3.2 Support

### ISSUE THREAD

**Issue by Mosnar** [vaersaagod/seomate#12]
I was taking some time to test this plugin for Craft 3.2 and it doesn't look like it's quite there. Particularly, the Live Preview functionality appears to be broken.

I started digging into it and found that the first issue is that the "Live Preview" button ID changed in 3.2, so that will need to be updated to:
```
var $lpBtn = $('#preview-btn');
```

After changing this, the button appeared as expected; however, clicking did nothing. I have not tested actual plugin rendering functionality yet; however, I that part doesn't seem likely to have broken. 

**Edit**
After additional digging, it looks like the LivePreview class is deprecated and the entire system is rewritten, so this may be a bit of a headache to fix.

**Comment by mmikkel** [comment]
This should be resolved in [SEOMate v1.0.5](https://github.com/vaersaagod/seomate/releases/tag/v1.0.5).
