### ISSUE TITLE
[3.2] Close SEO preview button is targeting the wrong elements

### ISSUE THREAD

**Issue by Mosnar** [vaersaagod/seomate#13]
Using SEOMate 1.0.5 in conjunction with MatrixMate is resulting in the "Close SEO Preview" button text being applied to the incorrect elements.
![image](https://user-images.githubusercontent.com/3810939/60626165-ef3f7480-9db7-11e9-9429-4077d3c34df5.png)

**Comment by mmikkel** [comment]
Ouch – nice catch @Mosnar. Should be fixed in [v1.0.6](https://github.com/vaersaagod/seomate/releases/tag/v1.0.6).
