### ISSUE TITLE
Properties returned by functions

### ISSUE THREAD

**Issue by piotrpog** [vaersaagod/seomate#14]
I tried to pass some string to title field instead of using values from fields. To do that i deduced i need to use function instead of field handle. Like it was showed in docs:

```
      'og:see_also' => function ($context) {
            $someLinks = [];
            $matrixBlocks = $context['globalSeo']->someLinks->all() ?? null;
            
            if ($matrixBlocks && count($matrixBlocks) > 0) {
                foreach ($matrixBlocks as $matrixBlock) {
                    $someLinks[] = $matrixBlock->someLinkUrl ?? '';
                }
            }
            
            return $someLinks;
        },
```

So i tried to test it, like this:

```
            'title' => function ($context) {
                return 'test';
        },
```

Unfortunetly it does not work, title takes value of site name if i try this.

**Comment by bleepsandblops** [comment]
Am having the exact same issue.

**Comment by mmikkel** [comment]
Rendering functions is actually a feature that's exclusive to `additionalMeta` (the docs could be clearer about that). However, I guess I can see how this feature could be useful to `fieldProfiles` or `defaultMeta`, so I'll label this as a feature request for now.

**Comment by mmikkel** [comment]
Support for closures (and Twig object templates) in `fieldProfiles` and `defaultMeta` has been added to SEOMate 3.0 (currently in beta) for Craft 5 🎉 

See the updated docs on the [`fieldProfiles` setting](https://github.com/vaersaagod/seomate/tree/dev/craft5?tab=readme-ov-file#fieldprofiles-array) for more info.
