### ISSUE TITLE
Make `additionalMeta` act as fallback instead of override

### ISSUE THREAD

**Issue by rungta** [vaersaagod/seomate#2]
Currently any values in the `additionalMeta` field end up overwriting values set in templates by creating an `seomate` object. Can the behaviour be altered to make the `additionalMeta` values act as defaults, which are used only if those fields are not already set either via the profile map, or via the template config? It would enable use cases such as this:

```php
/* config/seomate.php */
return [
   'additionalMeta' => [ 'og:type' => 'website' ],
];
```

```twig
{# template/news/_entry.twig #}
{% set seomate = {
   meta: { 'og:type': 'article' },
} %}
```

**Comment by aelvan** [comment]
Good point, moved `additionalMeta` earlier in the processing order so that it is overrideable from templates. Updated in v1.0.1.
