### ISSUE TITLE
Intendation issues

### ISSUE THREAD

**Issue by piotrpog** [vaersaagod/seomate#22]
It seems there are some intendation issues with code generated by plugin:

https://i.imgur.com/xxJDz7d.png

**Comment by mmikkel** [comment]
Hi @piotrpog, thanks for reporting. I don't think the inconsistent indentation matters much, but I went ahead and [cleaned it up](https://github.com/vaersaagod/seomate/commit/a6abd3b61e4bf49beff4ef7f8181c237a1f7dfc5) for the next release.
