### ISSUE TITLE
How to add relational fields to field profiles?

### ISSUE THREAD

**Issue by architchandra** [vaersaagod/seomate#25]
Can't seem to use values from a category or related entry in field profiles right now - had to use a custom template. It would be a good idea to have support for these through the config file itself. Thanks.

**Comment by aelvan** [comment]
Yeah, that is not currently supported, we'll look into adding it at some point.

**Comment by mmikkel** [comment]
In SEOMate 3.0 (currently in beta), values from relational fields can be used in field profiles via the new [object template](https://craftcms.com/docs/5.x/system/object-templates.html) support:

```php
'fieldProfiles' => [
    'default' => [
        'title' => ['{categoriesField.one().title}'],
    ],
]
```

See the updated docs for the [`fieldProfiles`](https://github.com/vaersaagod/seomate/tree/dev/craft5?tab=readme-ov-file#fieldprofiles-array) setting for more info.
