### ISSUE TITLE
FR: Support for noindex meta tag, per-environment

### ISSUE THREAD

**Issue by daltonrooney** [vaersaagod/seomate#26]
I'd love to be able to apply "noindex" to every page on my site based on the environment. This is specifically to prevent staging sites from ending up in the Google index, which seems to happen even when robots.txt is set to disallow.

If there were a simple way to set this per-page as well (based on a lightswitch field value, perhaps) that would be a nice bonus!

**Comment by aelvan** [comment]
This is something that we think is easier solved outside of a plugin like SEOMate. As you say, a lightswitch in entries, and some Twig-logic in your templates is all that's needed.
