### ISSUE TITLE
Template overrides in preview

### ISSUE THREAD

**Issue by tom-c** [vaersaagod/seomate#28]
First time using seomate and it's great - however I need to set a custom meta title on some entries which is comprised of some field data and custom string between. Thus using the template overrides seems the right way to go. 

When I apply template overrides they are not shown in the preview. I guess this might be a technical limitation but it seems a shame as the preview is great for a client to understand what they are doing.

I guess using a preparse field could be a work around?

Thanks 

Tom

**Comment by mmikkel** [comment]
Hi @tom-c, sorry for the late reply.

Right, this is a technical limitation. I concur having the SEO preview apply entry template overrides, the only solutions I can think of would be quite convoluted and difficult to implement (as well as adding complexity to the plugin – we're trying to keep this one as light and easily maintainable as possible).

Leaving this open, but it's not high on our priority list, sorry.

**Comment by mmikkel** [comment]
Only three short years later, [SEO previews should now render template overrides](https://github.com/vaersaagod/seomate/releases/tag/2.1.0) and custom meta templates 🎉
