### ISSUE TITLE
Access generated page title in twig

### ISSUE THREAD

**Issue by tom-c** [vaersaagod/seomate#31]
Sorry if I'm being daft but have looked through the source code and readme for a while with no luck. 

I'd like to be able to use the built meta title for a given page to log into some analytics, is there a way to output the title that seomate generates via twig in an entry template?

Thanks for your time

**Comment by aelvan** [comment]
v1.1.2 added a `craft.seomate.getMeta()` template variable which lets you get this.

**Comment by tom-c** [comment]
Amazing. Thank you so much 👍💯
