### ISSUE TITLE
additionalMeta setting not working

### ISSUE THREAD

**Issue by watarutmnh** [vaersaagod/seomate#32]
Everything work perfect except additionalMeta setting.
I add the setting as documented :
```
'additionalMeta' => [
        'og:type' => 'website',
        'twitter:card' => 'summary_large_image',
    ],
```
But it doesn't output tags..

My Environment:
PHP version | 7.3.6
MySQL 5.7.26
Craft Pro 3.3.19

**Comment by watarutmnh** [comment]
it solved after I clear the SEOMate cache from control panel.
sorry it should have been my mistake.

**Comment by mmikkel** [comment]
Hi @watarutmnh, thanks for the follow-up!
