### ISSUE TITLE
Add migration for common seo fields

### ISSUE THREAD

**Issue by piotrpog** [vaersaagod/seomate#33]
I was thinking about making seomate easier to use when starting new project.

How about adding migration for some common seo fields - like description, seo image and robots? I usually group these fields within matrix field that has max and min limit set to 1.

There could also be migratiln for global with page-wide seo settings.

Such migration would not be mandatory, but it would be usefull to have such thing.

**Comment by mmikkel** [comment]
Hi @piotrpog, thanks for contributing!

I feel like SEOMate shipping with content migrations would be require one too many assumptions on our part, so this is probably not going to happen.
