### ISSUE TITLE
SEO image - wrong URL

### ISSUE THREAD

**Issue by piotrpog** [vaersaagod/seomate#35]
Here is URL that seo image metatag had:

```
<meta property="og:image" content="http://bcweb.pl/test/esn/web/index.php?p=actions/assets/generate-transform&transformId=149">
```
And interestingly, transform WAS generated on server. But URL still stayed like this.

**Comment by aelvan** [comment]
This could happen if `generateTransformsBeforePageLoad` was set to `false`, and SEOMate caching was turned on. Fixed in 1.1.3, SEOMate will now force generation of image transforms.
