### ISSUE TITLE
How to generate image sitemap?

### ISSUE THREAD

**Issue by BrianBravo** [vaersaagod/seomate#37]
Is there a way to use this fantastic plugin to generate a sitemap for images and other assets in entries? 

https://support.google.com/webmasters/answer/178636?hl=en

**Comment by aelvan** [comment]
Not currently. Image sitemaps is a bit hard to pull off at scale, and is usually very site specific, so we haven't built something generic for SEOMate. You can still create it using a custom plugin, and add it to the index using the `additionalSitemaps` key in `sitemapConfig`.
