### ISSUE TITLE
How to overwrite image within a twig-template ?

### ISSUE THREAD

**Issue by amkdev** [vaersaagod/seomate#40]
```
       {% set seomate = {
            image: imageObject????
        } %}
```

Is it possible to overwrite the default image within a twig template?

I need to use the second image of an image field as default image on a special section type.

**Comment by aelvan** [comment]
When [overriding meta data](https://github.com/vaersaagod/seomate#overriding-meta-data-and-settings-from-your-templates), you do that within the `meta` key of the `seomate`, try:

``` 
{% set seomate = {
    meta: {
        image: asset
    }
} %}
```
