### ISSUE TITLE
open graph image - letterbox mode

### ISSUE THREAD

**Issue by piotrpog** [vaersaagod/seomate#42]
This is open graph image and image it was generated from:

https://imgur.com/a/nfkehQM

As you can see, image was cropped. This might cause problems in case of things like pictures of products in webshops - these pictures might be uploaded in specific proportions they might vary per product.

Letterbox is transform mode introduced by imager/imager-x plugin. It works by adding a white area on top and bottom/left and right parts of the image in order to fit it into a specific size.

I think it would be perfect for situations like this. Letterbox mode could be enabled per-template, so for example only product pages open graph images are generated like this.

**Comment by aelvan** [comment]
Hi,

You can customize the image transforms via the [imageTransformMap](https://github.com/vaersaagod/seomate#imagetransformmap-array) config setting. Setting it to something like this should do what you're asking, if you're using Imager:

```
[
    'image' => [
        'width' => 1200,
        'height' => 675,
        'format' => 'jpg',
        'mode' => 'letterbox', 
        'letterbox' => [ 'color' => '#ffffff', 'opacity' => 1 ]
    ],
    'og:image' => [
        'width' => 1200,
        'height' => 630,
        'format' => 'jpg',
        'mode' => 'letterbox', 
        'letterbox' => [ 'color' => '#ffffff', 'opacity' => 1 ]
    ],
    'twitter:image' => [
        'width' => 1200,
        'height' => 600,
        'format' => 'jpg',
        'mode' => 'letterbox', 
        'letterbox' => [ 'color' => '#ffffff', 'opacity' => 1 ]
    ],
]
```

This can also be overridden at the template level through the seomate object. 

Did that help?

**Comment by piotrpog** [comment]
@aelvan 
Yeah, thanks for info!
