### ISSUE TITLE
Open graph is not accepted by twitter or discord

### ISSUE THREAD

**Issue by piotrpog** [vaersaagod/seomate#46]
Hi!
I'm not sure if it is a problem with plugin or something else, but my website open graph is not accepted by twitter or discord. Heres example page:
http://craftsnippets.com/articles/matrix-within-a-matrix-possible-solutions-for-craft-cms

And here's twitter post with this link - it wasn't expanded into open graph image:
https://twitter.com/PiotrPogorzel/status/1297969538017955840

I tested my website with facebook open graph debugger and it seems ok:
https://developers.facebook.com/tools/debug/?q=http%3A%2F%2Fcraftsnippets.com%2Farticles%2Fmatrix-within-a-matrix-possible-solutions-for-craft-cms

edit:
after few minutes, open graph appeared on twitter, some maybe there's nothing wrong after all. But heres link to discord where link was not expanded:
https://discord.com/channels/456442477667418113/456445573097324555/747527997644472441

**Comment by aelvan** [comment]
Hi,

Not sure I understand what you mean with `...it wasn't expanded into open graph image`. Looking at your tweet, I can see the card for your article.

![image](https://user-images.githubusercontent.com/2675644/91086148-c7ac0b00-e64e-11ea-8aea-21508c9f4be6.png)

It also appears to validate In the Twitter card validator at https://cards-dev.twitter.com/validator.
