### ISSUE TITLE
Using Checkbox as Criteria

### ISSUE THREAD

**Issue by mattbloomfield** [vaersaagod/seomate#58]
Hi - I have a checkbox field on my entries that, when checked, removes them from the sitemap (or should). How do I handle that in the criteria? 

This works if I wanted to add them if it was checked: 

```php
'pageVisibility' => 'removeFromSitemap'
```

But I want to add them only if it's UNchecked. 

Thank you!

**Comment by mmikkel** [comment]
Hi @mattbloomfield - check out the official Craft docs on querying elements using checkbox field values - you should be able to use the same syntax for sitemap criteria in SEOmate:

https://craftcms.com/docs/3.x/checkboxes-fields.html#querying-elements-with-checkboxes-fields

**Comment by mattbloomfield** [comment]
Jaha, tak!
