### ISSUE TITLE
Eagerloading global images

### ISSUE THREAD

**Issue by nkpindolia** [vaersaagod/seomate#63]
I've got a global with my default seo image. `globalSeo.image`

I've got the [Element Panel](https://putyourlightson.com/plugins/elements-panel) plugin installed to check when i need to eager-load stuff or I've missed it out. It keeps showing a warning when the default image is added as the seo image that the image is not eagerloaded

**Comment by nkpindolia** [comment]
adding the following code in the config seems to fix the issue:

```
$globalSeo = Craft::$app->globals->getSetByHandle('myGlobalHandle');
Craft::$app->elements->eagerLoadElements('\craft\elements\GlobalSet', [$globalSeo], 'seoImageHandle');
```

however i now get a warning: "Element query executed before Craft is fully initialized."

**Comment by mmikkel** [comment]
Eager-loading a single element makes no sense as there is no N+1 query issue. In this case, eager-loading the global set would generate additional queries, not fewer.

If you're concerned about performance, make sure that the [SEOMate cache](https://github.com/vaersaagod/seomate#cacheenabled-bool) is enabled in live environments.
