### ISSUE TITLE
sitemap.xml not being generated

### ISSUE THREAD

**Issue by sonicfive** [vaersaagod/seomate#67]
Meta tags are being generated, but not an XML file for the sitemap. I am using the examples provided, but the file is not being generated.  I would appreciate your help.

**Comment by mmikkel** [comment]
Can you share your `config/seomate.php` file?

**Comment by sonicfive** [comment]
Sure!, thanks for helping.

`return [


'defaultProfile' => 'standard',

'fieldProfiles' => [
    'standard' => [
        'title' => ['title'],
        'description' => ['seoDescription', 'summary'],
        'image' => ['seoImage', 'mainImage']
    ],

    ],
'sitemapEnabled' => true,
'sitemapLimit' => 100,
'sitemapConfig' => [
    'elements' => [
        'news' => ['changefreq' => 'weekly', 'priority' => 1],
        'projects' => ['changefreq' => 'weekly', 'priority' => 0.5],
        'frontpages' => [
            'elementType' => \craft\elements\Entry::class,
            'criteria' => ['section' => ['homepage', 'newsFrontpage', 'projectsFrontpage']],
            'params' => ['changefreq' => 'daily', 'priority' => 1],
        ],
    ],
],

];`

**Comment by mmikkel** [comment]
@sonicfive The config looks legit, at a glance.

To be clear, the sitemap should be available via `https://yourdomain.com/sitemap.xml`. 

Specifically what happens when you visit that URL?

**Comment by sonicfive** [comment]
It was available all along when visiting `https://yourdomain.com/sitemap.xml`
My bad. I was expecting there to be an actual sitemap.xml in the root folder. 
Thanks for the help!

**Comment by mmikkel** [comment]
No problem @sonicfive – good to hear it's working!
