### ISSUE TITLE
Sitemap error from Google Console

### ISSUE THREAD

**Issue by olsp** [vaersaagod/seomate#68]
We submitted the sitemap to the Google Search Console but it gives an error. It says "Sitemap can be read, but has errors".
"Your Sitemap appear to be an HTML page. Please use a supported sitemap format instead."

Maybe that's because `<?xml version="1.0" encoding="UTF-8"?>` is missing in the file?

In other examples I also found this: `<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`

**Comment by aelvan** [comment]
Hi,

Both of those two should appear in the sitemaps that seomate generates. What does your sitemap look like, can you post the source here?

**Comment by olsp** [comment]
Sorry, I just looked at the "preview" in Firefox and they were not shown there, but when I look at the source code, they are present.

What can lead to Google thinking this is HTML?

**Comment by mmikkel** [comment]
Hi @olsp - circling back to this one, did you manage to resolve the problem?

**Comment by MisterMike** [comment]
Same here, there is an empty line (line 1) in the sitemap.xml on one of the websites I use it on, on other this line is not included.

**Comment by mmikkel** [comment]
@MisterMike Could you create a new issue for that, and include as much info as possible (i.e. Craft version, SEOMate version, sitemap source code etc)?

**Comment by MisterMike** [comment]
> @MisterMike Could you create a new issue for that, and include as much info as possible (i.e. Craft version, SEOMate version, sitemap source code etc)?

Thank you Mats, will do – but I first want to check if the issue is solved in Craft 4 (the working site has Craft 4), for that I unfortunately need to migrate away from SproutForm first (another story as everybody knows)

**Comment by mmikkel** [comment]
@MisterMike Great – FWIW I'm not able to reproduce the issue (i.e., empty line at the top of `sitemap.xml`) on either Craft 3 or 4.
