### ISSUE TITLE
Seomate overrides native craft live preview

### ISSUE THREAD

**Issue by knufri** [vaersaagod/seomate#69]
Hello,

I noticed a strange behaviour. The plugin works like normal but when I want use the build in craft live preview in the control panel there appears the seomate preview and not the craft live preview:

<img width="453" alt="Bildschirm­foto 2023-02-27 um 12 28 52" src="https://user-images.githubusercontent.com/2785206/221552584-ed5598c6-9dcc-42b7-b529-b53e68b7629b.png">
<img width="1865" alt="Bildschirm­foto 2023-02-27 um 12 29 13" src="https://user-images.githubusercontent.com/2785206/221552613-f3913138-7bd2-4f49-92c2-22b0ecae982e.png">

This also happens on the "View" Button which normally opens the entry view in a new tab.

Craft CMS 4.3.10
SEOMate 2.1.0
php 8.1

Has anyone the same problems? Here is my seomate.php file content:
```php
<?php
use craft\helpers\App;

return [
    'siteName' => App::env('SITE_NAME'),
    'defaultProfile' => 'default',
    'applyRestrictions' => true,

    'fieldProfiles' => [
        'default' => [
            'title' => ['seoTitle', 'title', 'headline'],
            'description' => ['seoDescription'],
            'image' => ['seoImage', 'image']
        ],
        'imprint' => [
            'title' => ['title'],
            'description' => null,
            'image' => null,
        ],
        'privacy' => [
            'title' => ['title'],
            'description' => null,
            'image' => null,
        ],
        'newsprofile' => [
            'title' => ['title'],
            'description' => ['newsSummary'],
        ]
    ],

    'profileMap' => [
        'news' => 'newsprofile',
    ],

    'metaPropertyTypes' => [
        'description,og:description,twitter:description' => [
            'type' => 'text',
            'minLength' => 50,
            'maxLength' => 160
        ],
        'image,og:image,twitter:image' => [
            'type' => 'image'
        ],
    ],

    'sitemapEnabled' => true,
    'sitemapConfig' => [
        'elements' => [
            'homepage' => ['changefreq' => 'weekly', 'priority' => 1],
            'pages' => ['changefreq' => 'weekly', 'priority' => 1],
            'news' => ['changefreq' => 'weekly', 'priority' => 1],
        ],
    ],
];
```

**Comment by mmikkel** [comment]
That will happen if there are no other preview targets defined, for the relevant section.

Do you have any preview targets defined in the section's settings?

**Comment by knufri** [comment]
Sorry @mmikkel,
it's monday 🙈 - thanks for your fast reply. I configured a preview target like this:

<img width="2258" alt="Bildschirm­foto 2023-02-27 um 13 08 14" src="https://user-images.githubusercontent.com/2785206/221560222-0e54f149-6fd1-4ad7-bdef-29975d7f65ed.png">

Now it works fine!

Best regards
Jan

**Comment by mmikkel** [comment]
@knufri Great, thanks for the follow-up and I'm happy you got it sorted :)
