### ISSUE TITLE
Switching from SEO preview to live preview without page refresh does not update the settings pane

### ISSUE THREAD

**Issue by Mosnar** [vaersaagod/seomate#7]
## Problem Description
If you click on the "SEO Preview" and then click on "Live Preview", the field settings are still displayed limited down to the SEO fields.

## Versions
SEOmate 1.0.2 
Craft CMS 3.1.28

**Comment by mmikkel** [comment]
Thanks for reporting, @Mosnar – and sorry for the delayed fix.

This should be resolved in SEOMate [v. 1.0.4](https://github.com/vaersaagod/seomate/releases/tag/v1.0.4).
