### ISSUE TITLE
Error message “Cannot unpack array with string keys”

### ISSUE THREAD

**Issue by rinusvandam** [vaersaagod/seomate#71]
## Issue
I'm running a few Craft sites on PHP 8.0.28 and I'm getting a “Cannot unpack array with string keys in” when previewing an entry. When I locally update the PHP version to 8.1+ it work's fine. But on production there's no way to update the PHP version. Is there any workaround for this? 

## System
- PHP version: 8.0.28
- OS version: Linux 4.18.0-305.17.1.lve.el8.x86_64
- Database driver & version: MariaDB 10.5.19
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-62)
- Craft edition & version: Craft Pro 4.4.13
- Yii version: 2.0.47
- Twig version: v3.4.3
- Guzzle version: 7.7.0

## Stacktrace
```
Error: Cannot unpack array with string keys in /var/www/html/vendor/vaersaagod/seomate/src/controllers/PreviewController.php:109
Stack trace:
#0 [internal function]: vaersaagod\seomate\controllers\PreviewController->actionPreview()
#1 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('preview', Array)
#4 /var/www/html/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction('seomate/preview...', Array)
#5 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seomate/preview...', Array)
#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(289): yii\web\Application->handleRequest(Object(craft\web\Request))
#7 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/html/public_html/index.php(12): yii\base\Application->run()
#9 {main}
```

**Comment by mmikkel** [comment]
Thanks for reporting that @rinusvandam. I'll get a fix out ASAP.

**Comment by rinusvandam** [comment]
Ha you're fast @mmikkel. Thank you!

**Comment by mmikkel** [comment]
@rinusvandam Should be all fixed in [SEOMate v. 2.1.2](https://github.com/vaersaagod/seomate/releases/tag/2.1.2). Thanks again for reporting.

**Comment by rinusvandam** [comment]
@mmikkel thank, just updated and all works fine now!

**Comment by mmikkel** [comment]
@rinusvandam Awesome, thanks for the follow-up!
