### ISSUE TITLE
Support for the Matrix sub field syntax in config/seomate.php has been deprecated

### ISSUE THREAD

**Issue by rinusvandam** [vaersaagod/seomate#72]
## Issue
I'm receiving a deprecation warning on one of our Craft sites: _Support for the matrixFieldHandle:blockTypeHandle.subFieldHandle Matrix sub field syntax in config/seomate.php has been deprecated. Use the syntax matrixFieldHandle.blockTypeHandle:subFieldHandle instead._

## System
- PHP version: 8.1.16
- OS Version: Linux 5.15.49-linuxkit
- Database driver & version: MariaDB 10.4.28
- Image driver & version: Imagick 3.7.0 (ImageMagick 6.9.11-60)
- Craft edition & version: Craft Pro 4.4.14
- Yii version: 2.0.47
- Twig version: v3.4.3
- Guzzle version: 7.7.0

**Comment by mmikkel** [comment]
Like the deprecation warning says, you should change any references to Matrix sub fields in your `config/seomate.php` file from the old syntax to the new syntax.

I.e. change anything that looks like this:

`matrixFieldHandle:blockTypeHandle.subFieldHandle`

to this:

`matrixFieldHandle.blockTypeHandle:subFieldHandle`

The old syntax still works as of SEOMate 2.x, but we'll probably remove it in the next major SEOMate version (likely 3.0 when Craft 5 is released), hence the deprecation warning.
