### ISSUE TITLE
sitemap.xml not being rendered

### ISSUE THREAD

**Issue by tsawitzki** [vaersaagod/seomate#8]
Hello, I can’t get the sitemap.xml to be rendered (in the web/ directory I suppose?), no file is created. This is my setup, maybe I missed a point on how to render the actual sitemap.xml file:

'
return [

    'sitenameSeparator' => '–',

    'defaultProfile' => 'standard',
    
    'fieldProfiles' => [
        'standard' => [
            'title' => ['seoTitle', 'heading', 'title'],
            'description' => ['seoDescription', 'projectDescription'],
            'image' => ['seoImage', 'mainImage']
        ]
    ],

    'sitemapEnabled' => true,
    'sitemapLimit' => 100,
    'sitemapConfig' => [
        'elements' => [
            'projects' => ['changefreq' => 'weekly', 'priority' => 0.5],
            'about' => ['changefreq' => 'weekly', 'priority' => 0.5],
        ],
    ],

];

'

**Comment by michaelhue** [comment]
No files will be created, the plugin adds a route to Craft for rendering the Sitemap.
Open http://your-craft-site.com/sitemap.xml in your browser and it should work.

**Comment by tsawitzki** [comment]
Ah, I see … But why does it reference the Channel and Single pages with separate sitemaps?
This is what I get ("url" just for obfuscating reasons):

`<sitemapindex><!--Created on: 2019-06-14 04:16:06--><sitemap><loc>https://url/sitemap-projects-1.xml</loc><lastmod>2019-06-13T03:20:16-07:00</lastmod></sitemap><sitemap><loc>https://url/sitemap-about-1.xml</loc><lastmod>2019-06-10T10:04:39-07:00</lastmod></sitemap></sitemapindex>`

**Comment by michaelhue** [comment]
The plugin creates a separate sitemap for every section.

Check https://www.sitemaps.org/protocol.html for more info on how sitemaps work.

**Comment by tsawitzki** [comment]
Thanks for the information and the great plugin!

**Comment by rtgoodwin** [comment]
I know this is closed but maybe wouldn't hurt to add to the Readme for simpletons like me that also kept searching for the sitemap.xml? :) Thanks for all the work on this!
