### ISSUE TITLE
trimming 'description' text — an idiots guide?!

### ISSUE THREAD

**Issue by MattAppleton** [vaersaagod/seomate#81]
Hello — fantastic plugin, which is doing everything I want so far, bar one thing...

I'd like the 'description' text to fall back to my 'mainContent' field if it isn't set. Which works fine, but... often this is a very long text! How do I trim this?

I found your documentation about how to set the parameters, in my case I have:

```
'description,og:description,twitter:description, mainContent' => [
        'type' => 'text',
        'minLength' => 50,
        'maxLength' => 300
    ],
```

but if I place this in my seomate.php file, it doesn't do anything, perhaps I need a custom meta template? 
Just not sure how  / where to make this?

Any help much appreciated!

**Comment by aelvan** [comment]
You also need to set [`applyRestrictions`](https://github.com/vaersaagod/seomate?tab=readme-ov-file#applyrestrictions-bool) to `true` for those to take effect.
