### ISSUE TITLE
How to get matrix field value from global?

### ISSUE THREAD

**Issue by piotrpog** [vaersaagod/seomate#9]
I have such setup that was made based on docs and it results in empty meta description.

```
    'defaultMeta' => [
            'description' => ['seo.seoFields:settings.globalDescription'],
    ],
```
`seo` is handle of global, `seoFields` is handle of matrix field, `settings` is handle of matrix block, `globalDescription` is handle of subfield within matrix.

Am I doing something wrong?

**Comment by aelvan** [comment]
Support for this was added in v1.0.3.
